### ISSUE TITLE
Cell-type disease association vs proportion of significant cells

### ISSUE THREAD

**Issue by DanielYuhangLi** [martinjzhang/scDRS#43]
Thanks for this tool, has been fun and insightful to use. Sorry if this was covered in the paper but I was just wondering what are some plausible reasons if there is significant cell-type disease association but the proportion of significant cells are very low. I see in the extended example there are some traits with a box for cell-type disease association but minimal significant cells.

Thanks for your time,
Dan

**Comment by martinjzhang** [comment]
Hi Dan,

Thank you for the question. The reason is that we have higher power for detecting cell type-disease associations than individual cell-disease associations, because the former can aggregate results across cells in the cell type in a fashion similar to meta-analysis. Consider the example where all cells in a given cell type have moderately large disease scores. Since the disease scores are not large enough, no individual cell is significantly associated with disease after FDR correction. However, the cells may collectively suggest that the focal cell type is more relevant to disease than other cell types. As a result, the proportion of significant cells may be low for cell types associated with the disease. 

In multiple hypothesis testing, this is related to the fact that it requires less power to reject the global null (at least one hypothesis is alternative) than to reject individual hypotheses. 

Please let us know if this is not clear. 

Best,
Martin

**Comment by DanielYuhangLi** [comment]
Thanks so much, appreciate the input. It makes sense, it seems the heritability scores for the neurologic diseases are much higher than what I have been looking at which possibly contributes to these resuts.
